### PR TITLE
Help on splitting objects

### PR DESCRIPTION
**Pull request by carlopav**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by carlopav** [comment]
hey there @vocx-fc ! perhaps i did not have to rebase your branch?

**Comment by vocx-fc** [comment]
Are you basing this off my `BaseObject` branch? Please notice that I created this branch many months ago, and I haven't tested it lately. So, you may want to test it first. It's a single commit.

This `BaseObject` branch is currently on top of other branches that haven't been merged yet. In particular #3308, so it has many commits that aren't merged yet.

When you start your branch, make sure you have everything up to date. Currently my branches aren't completely up to date, so I may have to do this before you can use it as well, otherwise it will cause a bunch of issues.

**Comment by carlopav** [comment]
hmm, what I did is to clone your branch, rebase it to upstream/master and push the 2 commits you see here. 

What do you suggest?

**Comment by vocx-fc** [comment]
Basically, if you are going to use this branch as base, then I should not rebase it further. It means we have to coordinate very well because if I rebase this branch, your edits will break.

So, I suggest you create a new branch from the master code, then copy my edits, and then develop your own code on your own. This is pretty much what we've been doing the last months. We develop independently, and at the end, we mix everything together with pull requests. Then you don't have to wait for me. Sorry, I've been a bit busy these days so I haven't had time to play with the code. So that's why I've been slow.

**Comment by carlopav** [comment]
> Sorry, I've been a bit busy these days so I haven't had time to play with the code. So that's why I've been slow.

No problem, I do not want to push you: since you helped me several times with revisions, I'd like to help you a bit with this boring stuff too!

Ok, I'll do as you suggest!

**Comment by vocx-fc** [comment]
Okay, now I rebased this branch, so it is really at the top and doesn't contain old commits. It follows after FreeCAD#3308. Now you may use it as base.

**Comment by carlopav** [comment]
Good!
My branch is: https://github.com/carlopav/FreeCAD/tree/SplitDraftObjects
It is rebased over your https://github.com/vocx-fc/FreeCAD/tree/BaseObject
I won't make a PR until I have a bunch of objects splitted to leave Travis quiet :)

**Comment by vocx-fc** [comment]
Please check the `DraftObject` class, which is the parent class of most others. If you can verify that this works correctly, then I think most other classes will work fine. And open and close the test file in `data/examples/` many times to verify that there are no broken elements. Also the view providers, of course, `ViewProviderDraft` and all.

**Comment by carlopav** [comment]
> 
> 
> Please check the `DraftObject` class, which is the parent class of most others. If you can verify that this works correctly, then I think most other classes will work fine. And open and close the test file in `data/examples/` many times to verify that there are no broken elements. Also the view providers, of course, `ViewProviderDraft` and all.

After splitting every object I run the test to make new objects and I also open the test file generated before the splitting. Everything works really fine at the moment.

**Comment by vocx-fc** [comment]
Okay. I also suggest you test opening the Arch and BIM workbenches, and even your older files, because we never know if we are missing something in a real file.

**Pull request closed without merging**
